// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bilfqlcylzhcahvoodvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpbGZxbGN5bHpoY2Fodm9vZHZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODQwMDgsImV4cCI6MjA1OTk2MDAwOH0.osmxgTf-GTBrPPwSTMXFi17K8UG9_F9_HM-4dKGe73U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);